sudo: required
services:
        - docker
before_install:
        - docker build  -t sashakil/react-app -f Dockerfile.dev .

script:
        - docker run --env CI=true sashakil/react-app npm run test
